package instructor;

import ood.MainFacadeInterface;

public class instructorInterface extends javax.swing.JFrame {
    
    String courseName = "";
    String courseNumber = "";
    boolean newCourseCreated = false;
    /**
     * Creates new form ClassUI
     */
    public instructorInterface() {
        initComponents();
        //SP side
        labelSPUload.setVisible(false);
        inputSPUloadDate.setVisible(false);
        labelSPExp.setVisible(false);
        inputSPExpDate.setVisible(false);
        //Semester side
        labelSSemester.setVisible(false);
        labelSDuration.setVisible(false);
        labelSCredit.setVisible(false);
        labelSCertification.setVisible(false);
        labelSInstructor.setVisible(false);
        inputSSemeter.setVisible(false);
        inputSDuration.setVisible(false);
        inputSCredit.setVisible(false);
        inputSCertification.setVisible(false);
        inputSInstructor.setVisible(false); 
        
        
        jLabel10.setText(MainFacadeInterface.state);
        
        if (MainFacadeInterface.state == "Maintenance")
        {
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            inputCourseName.setVisible(false);
            inputCourseFee.setVisible(false);
            inputCourseUniv.setVisible(false);
            inputCourseSubject.setVisible(false);

            uiConfimationText.setVisible(false);
            jComboBox1.setVisible(false);
            buttonClear.setVisible(false);
            buttonSubmit.setVisible(false);
            
            jLabel8.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSubmit = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputCourseUniv = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputCourseName = new javax.swing.JTextField();
        inputCourseFee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputCourseSubject = new javax.swing.JTextField();
        uiConfimationText = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labelSPUload = new javax.swing.JLabel();
        labelSPExp = new javax.swing.JLabel();
        inputSPUloadDate = new javax.swing.JTextField();
        inputSPExpDate = new javax.swing.JTextField();
        labelSSemester = new javax.swing.JLabel();
        labelSDuration = new javax.swing.JLabel();
        labelSCredit = new javax.swing.JLabel();
        labelSCertification = new javax.swing.JLabel();
        labelSInstructor = new javax.swing.JLabel();
        inputSSemeter = new javax.swing.JTextField();
        inputSDuration = new javax.swing.JTextField();
        inputSCredit = new javax.swing.JTextField();
        inputSCertification = new javax.swing.JTextField();
        inputSInstructor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        jLabel2.setText("Select type of course");

        jLabel3.setText("Confirmation");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Self-Pace", "Semester" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter name of course");

        inputCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseNameActionPerformed(evt);
            }
        });

        inputCourseFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseFeeActionPerformed(evt);
            }
        });

        jLabel5.setText("Fee");

        jLabel6.setText("University");

        jLabel7.setText("Enter subject");

        uiConfimationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiConfimationTextActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        jLabel8.setText("Additional Information");

        labelSPUload.setText("Upload date");

        labelSPExp.setText("Expiration date");

        inputSPUloadDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSPUloadDateActionPerformed(evt);
            }
        });

        labelSSemester.setText("Semester");

        labelSDuration.setText("Duration");

        labelSCredit.setText("Credit");

        labelSCertification.setText("Certification");

        labelSInstructor.setText("Instructor");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setText("Welcome!");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel12.setText("Online learning made simple with \"Learn All the Things\" academy!");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Status:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Open");

        jLabel11.setText("Course Number");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputCourseFee)
                            .addComponent(inputCourseUniv)
                            .addComponent(inputCourseSubject)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(inputCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSPUload)
                    .addComponent(labelSPExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSPUloadDate, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(inputSPExpDate))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSDuration)
                    .addComponent(labelSSemester)
                    .addComponent(labelSCredit)
                    .addComponent(labelSCertification)
                    .addComponent(labelSInstructor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSInstructor)
                    .addComponent(inputSCertification, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputSSemeter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(inputSDuration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(inputSCredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(uiConfimationText, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 687, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel10))
                            .addComponent(jLabel8))
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSPUload)
                            .addComponent(inputSPUloadDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSSemester)
                            .addComponent(inputSSemeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSPExp)
                            .addComponent(inputSPExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSDuration)
                            .addComponent(inputSDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSCredit)
                            .addComponent(inputSCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSCertification)
                            .addComponent(inputSCertification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSInstructor)
                            .addComponent(inputSInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputCourseFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputCourseUniv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inputCourseSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiConfimationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSubmit)
                    .addComponent(buttonExit)
                    .addComponent(buttonClear)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    

        
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
//            jComboBox1.addActionListener (new ActionListener () {
  //            public void actionPerformed(ActionEvent e) {
                  
                     if(jComboBox1.getSelectedItem( ).toString().equals("Self-Pace")){
                            //SP side
                            labelSPUload.setVisible(true);
                            inputSPUloadDate.setVisible(true);
                            labelSPExp.setVisible(true);
                            inputSPExpDate.setVisible(true);
                            
                                                        //Semester side
                            labelSSemester.setVisible(false);
                            labelSDuration.setVisible(false);
                            labelSCredit.setVisible(false);
                            labelSCertification.setVisible(false);
                            labelSInstructor.setVisible(false);
                            inputSSemeter.setVisible(false);
                            inputSDuration.setVisible(false);
                            inputSCredit.setVisible(false);
                            inputSCertification.setVisible(false);
                            inputSInstructor.setVisible(false);  
                            
                    }
                     if (jComboBox1.getSelectedItem( ).toString().equals("Semester")){
                         //SP side
                            //Semester side
                            labelSSemester.setVisible(true);
                            labelSDuration.setVisible(true);
                            labelSCredit.setVisible(true);
                            labelSCertification.setVisible(true);
                            labelSInstructor.setVisible(true);
                            inputSSemeter.setVisible(true);
                            inputSDuration.setVisible(true);
                            inputSCredit.setVisible(true);
                            inputSCertification.setVisible(true);
                            inputSInstructor.setVisible(true);  
                            
                            //SP side
                            labelSPUload.setVisible(false);
                            inputSPUloadDate.setVisible(false);
                            labelSPExp.setVisible(false);
                            inputSPExpDate.setVisible(false);
                     }
     //           }
       //     });      
    }//GEN-LAST:event_jComboBox1ActionPerformed


    
    
    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
       FactoryBuildingForm MakeCourse = new FactoryBuildingForm();
       
       if (jComboBox1.getSelectedItem( ).toString().equals("Self-Pace"))
       {
        Course myCourseObj = MakeCourse.createCourse((String)jComboBox1.getSelectedItem( ), jTextField1.getText(),
                inputCourseName.getText(),  Double.parseDouble(inputCourseFee.getText()), 
                inputCourseUniv.getText(), inputCourseSubject.getText(), 
                inputSPUloadDate.getText(), inputSPExpDate.getText());
                uiConfimationText.setText(String.valueOf(myCourseObj.getName())+ " was sucesfully created");
        newCourseCreated = true;
       }
       else 
       {
           Course myCourseObj = MakeCourse.createCourse((String)jComboBox1.getSelectedItem( ), jTextField1.getText(),
                   inputCourseName.getText(), Double.parseDouble(inputCourseFee.getText()), 
                   inputCourseUniv.getText(), inputCourseSubject.getText(), 
                   inputSSemeter.getText(), Double.parseDouble(inputSDuration.getText()), 
                   Double.parseDouble(inputSCredit.getText()), 
                   inputSCertification.getText(), inputSInstructor.getSelectedText());
                   uiConfimationText.setText(String.valueOf(myCourseObj.getName())+" was sucesfully created");
           newCourseCreated = true;
       }
       
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void inputCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseNameActionPerformed

    private void inputCourseFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseFeeActionPerformed

    private void uiConfimationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiConfimationTextActionPerformed
        //
    }//GEN-LAST:event_uiConfimationTextActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        inputCourseName.setText("");
        inputCourseFee.setText("");
        inputCourseUniv.setText("");
        inputCourseSubject.setText("");
        inputSSemeter.setText("");
        inputSDuration.setText("");
        inputSCredit.setText("");
        inputSCertification.setText("");
        inputSInstructor.setText("");
        inputSPUloadDate.setText("");
        inputSPExpDate.setText("");
        uiConfimationText.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void inputSPUloadDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSPUloadDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSPUloadDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        MainFacadeInterface mainInterface = new MainFacadeInterface();
        //mainInterface.setState(state);
        if (newCourseCreated)
        {
            mainInterface.setCourseName(inputCourseName.getText());
            mainInterface.setCourseNumber(jTextField1.getText());
            mainInterface.setCourseType(jComboBox1.getSelectedItem().toString());
        }
        
        mainInterface.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructorInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JTextField inputCourseFee;
    private javax.swing.JTextField inputCourseName;
    private javax.swing.JTextField inputCourseSubject;
    private javax.swing.JTextField inputCourseUniv;
    private javax.swing.JTextField inputSCertification;
    private javax.swing.JTextField inputSCredit;
    private javax.swing.JTextField inputSDuration;
    private javax.swing.JTextField inputSInstructor;
    private javax.swing.JTextField inputSPExpDate;
    private javax.swing.JTextField inputSPUloadDate;
    private javax.swing.JTextField inputSSemeter;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelSCertification;
    private javax.swing.JLabel labelSCredit;
    private javax.swing.JLabel labelSDuration;
    private javax.swing.JLabel labelSInstructor;
    private javax.swing.JLabel labelSPExp;
    private javax.swing.JLabel labelSPUload;
    private javax.swing.JLabel labelSSemester;
    private javax.swing.JTextField uiConfimationText;
    // End of variables declaration//GEN-END:variables
}
